# Generated by Django 2.2 on 2022-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='plan name', max_length=100, null=True)),
                ('plan_range', models.CharField(blank=True, choices=[('M', 'Monthly')], default='M', help_text='M=Monthly', max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='activate/deactivate plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Subscription',
                'db_table': 'subscription',
            },
        ),
    ]
