# Generated by Django 2.2 on 2022-02-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_active',
            new_name='is_deleted',
        ),
    ]
