# Generated by Django 2.2 on 2022-02-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonData', '0002_auto_20220205_1433'),
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Cancel', 'Cancel')], default='Active', help_text='Status of the Plan', max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('F', 'Failed'), ('S', 'Success')], default='F', help_text='Payment Status', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonData.Subscription')),
            ],
            options={
                'verbose_name_plural': 'Book Subscription',
                'db_table': 'book_subscription',
            },
        ),
    ]
