# Generated by Django 2.2 on 2022-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_booksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksubscription',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancel', 'Cancel'), ('Active', 'Active')], default='Cancel', help_text='Status of the Plan', max_length=20, null=True),
        ),
    ]
